### ISSUE TITLE
Test suite fails

### ISSUE THREAD

**Issue by speth** [uw-comphys/openccm#41]
Most of the tests fail when I run them (`main` branch, commit 8ba12ae).

First, I note that the correct way to run the tests does not appear to be documented -- it requires running `pytest` from the `pytests` subdirectory, and does not work if you run `pytest pytests/` from the root directory of the source tree.

The short summary of failures is as follows:

```
=============================== short test summary info ================================
FAILED test_run_examples.py::test_opencmp_cstr_reversible - NameError: name 'np' is not defined
FAILED test_run_examples.py::test_opencmp_cstr_irreversible - NameError: name 'np' is not defined
FAILED test_run_examples.py::test_opencmp_pfr - NameError: name 'np' is not defined
FAILED test_run_examples.py::test_opencmp_recirc - NameError: name 'np' is not defined
FAILED test_run_examples.py::test_openfoam_2d_pipe - ValueError: Specified folder (../examples/OpenFOAM/pipe_with_recirc/./) does not co...
======================== 5 failed, 1 passed, 1 warning in 3.13s ========================
```

The full output of `pytest -v .` is here:[testlog.txt](https://github.com/user-attachments/files/16645716/testlog.txt)

I am not sure what the requirements for running the test suite are. Does it require that both OpenCMP and OpenFOAM are also installed? It might be better to include some small example input data that can be used for testing, rather than requiring a rather large dependency to be installed. 

This is in the context of the review for JOSS (https://github.com/openjournals/joss-reviews/issues/6963).

**Comment by Alex-Vasile** [comment]
Hi @speth.

I'll be putting up a PR for this soon, see my comments below.

- [x] I have included instructions specifying where to run the tests from.
- [x] Most of the failures are due to the a numpy change when going from 1.2 to 2.0. #39 addresses it.
- [x] The OpenFOAM failure was caused by unavailable velocity profiles. I have included one and modified the run instructions for it accordingly.
- [x] I have also included code for auto-running OpenCMP for generating the data needed for the tests when they are run.
- [x] Re: Requirements. For the currently available OpenFOAM tests I have included the velocity data required in native OpenFOAM format, but do not want to generally do this as the file sizes will quickly get out of hand. In order to run all of the tests OpenCMP is required to be installed. I have changed the OpenCMP tests to be skipped if OpenCMP is not installed if the end user only cares about OpenFOAM support. The need for OpenCMP installed for it's test are:
1. OpenCMP functionality is leveraged for file I/O.
2. We have considered including OpenCMP in our intermediary format, but that would require re-processing whenever the intermediary format or the conversion process is changed. Further,  the tests would no longer be hitting the conversion steps. Finally it would increase the size of the repository and of the final installed package.

**Comment by Alex-Vasile** [comment]
Hi @speth , let me know if the changes from #45 address your comments.

**Comment by speth** [comment]
Hi @Alex-Vasile, I am now able to run the test suite successfully. However, I noticed that while the tests run several examples, there are no assertions in any of the tests that would check that the software is generating the expected results. The test suite would pass as long as the example doesn't terminate with an error of some sort.

**Comment by Alex-Vasile** [comment]
Hi @speth, That is partially correct. Yes, there were no asserts written in `test_run_example.py` itself. However, the functions inside the package contain their own asserts to guarantee expected properties of the input/output.

For example, the bottom of `_merge_connections` contains the following checks:
https://github.com/uw-comphys/openccm/blob/d8e29d1976c9b92bb74206c883f064e4fc93aed3/openccm/compartment_models/pfr.py#L616-L645

Similar checks are included across the majority of functions in the package. So, just by running different examples much of the code is tested and each functions' asserts are passed. Having the example run means that many individual tests are passed throughout the package.

To expand on that, I have added, in #52, some explicit asserts to the example files which will now check the output of the simulations.

**Comment by speth** [comment]
Thanks, I see. Perhaps a bit unconventional as a testing strategy, but I think it's sufficient for the JOSS review requirements. In the long run, I might suggest thinking about also using more explicit unit and regression tests.
